modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"
issueTrackerURL="https://github.com/Su5eD/Lazurite/issues"

[[mods]]
modId="lazurite"
version="${file.jarVersion}"
displayName="Lazurite"
logoFile= "../assets/lazurite/icon.png"
authors="Su5eD"
credits="comp500"
displayURL="https://github.com/Su5eD/Lazurite"
description='''
Forge port of Indium, a Sodium addon providing support for the Fabric Rendering API, based on Indigo.
'''
displayTest = "IGNORE_SERVER_VERSION"
# FFLoader attribute
provides = ["indium"]

[modproperties.lazurite]
"fabric-renderer-api-v1:contains_renderer"=true

[[dependencies.lazurite]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lazurite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lazurite]]
    modId="embeddium"
    mandatory=true
    versionRange="[0.2.5, 0.4)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lazurite]]
    modId="fabric_renderer_api_v1"
    mandatory=true
    versionRange="[0, )"
    ordering="NONE"
    side="BOTH"
[[dependencies.lazurite]]
    modId="fabric_resource_loader_v0"
    mandatory=true
    versionRange="[0, )"
    ordering="NONE"
    side="BOTH"
[[dependencies.lazurite]]
    modId="fabric_block_view_api_v2"
    mandatory=true
    versionRange="[0, )"
    ordering="NONE"
    side="BOTH"
[[dependencies.lazurite]]
    modId="fabric_rendering_data_attachment_v1"
    mandatory=true
    versionRange="[0, )"
    ordering="NONE"
    side="BOTH"
