modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"
issueTrackerURL="https://github.com/Su5eD/Indium/issues"

[[mods]]
modId="indium"
version="${file.jarVersion}"
displayName="Indium"
logoFile="assets/indium/icon.png"
authors="Su5eD"
credits="comp500"
displayURL="https://github.com/Su5eD/Indium"
description='''
Sodium addon providing support for the Fabric Rendering API, based on Indigo
'''
displayTest = 'IGNORE_SERVER_VERSION'

[modproperties.indium]
"fabric-renderer-api-v1:contains_renderer"=true

[[dependencies.indium]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.indium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
