blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Su5eD/Lazurite/discussions
    about: Please look here for frequently asked questions and questions on how to use Lazurite.
  - name: Discord
    url: https://discord.gg/mamk7z3TKZ
    about: Join us on our discord!